### ISSUE TITLE
Can't install cuda 11.1

### ISSUE THREAD

**Issue by M-Usamah** [amirtronix/parrot_ros#1]
Hi i am having this issue
![image](https://github.com/user-attachments/assets/de98ec7b-526c-4e09-9c3b-371a167cd47b)

how can i solve it

**Comment by amirtronix** [comment]
Would it pop up the driver selection windows once you select 'continue'?

**Comment by M-Usamah** [comment]
No it will Abort

**Comment by amirtronix** [comment]
Run `nvidia-smi` and share the output here as well ass the cuda version you're trying to install. let me know what Ubuntu station you're at (20 or 22).

**Comment by M-Usamah** [comment]
I am running Pop os which is based on ubuntu 
![image](https://github.com/user-attachments/assets/7e74d34c-649f-4ed7-b206-9badd1ae1cb3)

and i have pre build nvidia driver
![image](https://github.com/user-attachments/assets/7501f319-0982-4d25-82ba-6fcc4aefac2e)

but if i try to install nvidia 530 it will install 535

**Comment by amirtronix** [comment]
Try installing cuda 12.1 for ubuntu 22 from this [link](https://developer.nvidia.com/cuda-12-1-1-download-archive?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=22.04&target_type=runfile_local). It could be driver/cuda compatibility issue.

**Comment by M-Usamah** [comment]
when I run nvidia-smi it is giving me this response  
![image](https://github.com/user-attachments/assets/ddf98580-c529-4f7d-8477-2dcd2d689f35)

**Comment by M-Usamah** [comment]
Thank you it worked
